sudo: required
dist: trusty

language: python

cache:
  directories:
    - $HOME/virtualenv/python3.4.3

env:
  global:
    # Dependencies
    - DEPS_DIR="`readlink -f $TRAVIS_BUILD_DIR/..`"
    - OPENCV_BUILD_DIR=$DEPS_DIR/opencv/build

before_install:
  - bash .install-opencv.sh

python:
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script:
  - python robot.py coverage test
after_script:
  - coveralls
notifications:
  slack: frc-4774:gtsMx8XEC0U9v61da4RJd7fT
